In [28]:
import numpy as np
import pandas as pd

In [29]:
cards_df = pd.read_csv("Cards_Data.csv")
cards_df.head()

,Card_ID,Customer_ID,Card_Type,Card_Network,Credit_Limit,Card_Status,Contactless,Card_Mode,Issue_Date,Expiry_Date
0,CARD500001,CUST100001,Gold,RuPay,587317,Active,Yes,Physical,2021-04-24,2026-04-24
1,CARD500002,CUST100002,Silver,Visa,150720,Active,Yes,Virtual,2020-06-30,2025-06-30
2,CARD500003,CUST100003,Gold,RuPay,631005,Active,Yes,Physical,2022-04-04,2027-04-04
3,CARD500004,CUST100004,Silver,Mastercard,285015,Expired,Yes,Virtual,2020-07-21,2025-07-21
4,CARD500005,CUST100005,Gold,Mastercard,348591,Active,Yes,Physical,2024-07-24,2029-07-24

In [30]:
cards_df.shape

(32457, 10)

In [31]:
print(cards_df[cards_df.duplicated(subset=['Card_ID'])])

Empty DataFrame
Columns: [Card_ID, Customer_ID, Card_Type, Card_Network, Credit_Limit, Card_Status, Contactless, Card_Mode, Issue_Date, Expiry_Date]
Index: []

In [32]:
customers_df = pd.read_csv("Cusmtomer_data.csv")
customers_df.head()

,Customer_ID,Customer_Name,Gender,Age,Marital_Status,Occupation,Annual_Income,Customer_Segment,State,City,Account_Type,Customer_Since
0,CUST100001,Omaja Majumdar,Female,27,Single,Police Officer,1167132,Gold,Uttar Pradesh,Agra,Savings,2017-11-13
1,CUST100002,Jason Agrawal,Female,41,Married,Teacher,493532,Standard,Madhya Pradesh,Ujjain,Salary,2020-05-05
2,CUST100003,Amrita Dora,Male,61,Divorsed,Business,1862614,Platinum,Assam,Silchar,Savings,2023-08-23
3,CUST100004,Radhika Batra,Male,26,Single,Software Engineer,808153,Gold,Uttar Pradesh,Ghaziabad,Salary,2018-05-21
4,CUST100005,Gautam Mukhopadhyay,Female,24,Single,Software Engineer,1581447,Platinum,Rajasthan,Jodhpur,Salary,2017-04-16

In [33]:
customers_df.shape

(25000, 12)

In [34]:
print(customers_df[customers_df.duplicated(subset=['Customer_ID'])])

Empty DataFrame
Columns: [Customer_ID, Customer_Name, Gender, Age, Marital_Status, Occupation, Annual_Income, Customer_Segment, State, City, Account_Type, Customer_Since]
Index: []

In [35]:
merchants_df = pd.read_csv("merchant_table.csv")
merchants_df.head()

,Merchant_ID,Merchant_Name,Merchant_Category,State,City,Merchant_Risk_Level,Merchant_Rating,Merchant_Status,Merchant_Since
0,MER100001,Paytm Utilities,Utilities,Haryana,Gurugram,Medium,4.8,Active,2012-07-29
1,MER100002,Coursera,Education,Bihar,Patna,Low,4.3,Active,2008-03-09
2,MER100003,Redbus,Travel,Bihar,Muzaffarpur,Low,4.7,Active,2006-08-12
3,MER100004,Air India,Airline,Tamil Nadu,Salem,Low,3.6,Active,2008-03-30
4,MER100005,IndiGo,Airline,Punjab,Jalandhar,Medium,4.1,Active,2007-07-18

In [36]:
merchants_df.shape

(500, 9)

In [37]:
print(merchants_df[merchants_df.duplicated(subset=['Merchant_ID'])])

Empty DataFrame
Columns: [Merchant_ID, Merchant_Name, Merchant_Category, State, City, Merchant_Risk_Level, Merchant_Rating, Merchant_Status, Merchant_Since]
Index: []

In [38]:
transactions_df= pd.read_csv("Transaction_Data_250k.csv")
transactions_df.head()

,Transaction_ID,Customer_ID,Card_ID,Merchant_ID,Transaction_Date,Transaction_Time,Transaction_Amount,Payment_Method,Transaction_Channel,Device_Type,Transaction_Status,Is_International,Fraud_Flag,Fraud_Reason,Merchant_Risk_Level,Merchant_Category,Customer_State,Customer_City,Merchant_State,Merchant_City
0,TXN1000001,CUST100660,CARD500875,MER100380,2024-03-03,05:50:10,21748.02,Debit Card,Mobile App,Android Mobile,Successful,1,0,NaN,Low,Hotel,Tamil Nadu,Madurai,Tamil Nadu,Salem
1,TXN1000002,CUST111388,CARD514772,MER100017,2023-11-08,06:55:15,9960.60,Debit Card,POS,POS Terminal,Successful,0,0,NaN,Low,Travel,Kerala,Kollam,Haryana,Nuh
2,TXN1000003,CUST115872,CARD520625,MER100143,2023-01-11,02:17:28,838.61,Debit Card,ATM,ATM Machine,Successful,0,0,NaN,Low,Food Delivery,Uttar Pradesh,Agra,West Bengal,Kolkata
3,TXN1000004,CUST109049,CARD511773,MER100053,2023-05-25,01:48:56,52694.99,Credit Card,POS,POS Terminal,Successful,0,0,NaN,Low,Financial Services,Punjab,Ludhiana,Madhya Pradesh,Indore
4,TXN1000005,CUST114459,CARD518771,MER100064,2023-10-22,00:23:32,1043.40,Debit Card,Online Web,Android Mobile,Successful,0,0,NaN,Low,Entertainment,Maharashtra,Thane,Madhya Pradesh,Jabalpur

In [40]:
transactions_df.shape

(250000, 20)

In [ ]:
transactions_df.drop['Customer_ID']